name: Rust

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Build
      run: |
        cargo build --verbose --bin display

    - uses: actions/upload-artifact@v4
      with:
        name: mac-bin 
        path: target/debug/display

    - name: Debug with tmate on failure
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: ilammy/setup-nasm@v1

    - uses: msys2/setup-msys2@v2
      with:
        update: true

    - uses: actions/checkout@v4
  
    - name: Install pthreads
      shell: msys2 {0}
      run: |
        pacman -Sy --noconfirm gcc

    - name: Build
      run: |
        cargo build --verbose --bin display

    - uses: actions/upload-artifact@v4
      with:
        name: windows-bin
        path: target/debug/display.exe

    - name: Debug with tmate on failure
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
