name: Rust

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Build
      run: |
        cargo build --verbose --bin display

    - uses: actions/upload-artifact@v4
      with:
        name: mac-bin 
        path: target/debug/display

    - name: Debug with tmate on failure
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Install pkg-config & vcpkg
      run: |
        vcpkg integrate install

    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Get ffmpeg libraries
      run: |
        vcpkg install ffmpeg

    - name: Build
      run: |
        cargo build --verbose --bin display

    - uses: actions/upload-artifact@v4
      with:
        name: windows-bin
        path: target/debug/display.exe

    - name: Debug with tmate on failure
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
