name: Rust

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Build
      run: |
        cargo build --verbose --bin display

    - uses: actions/upload-artifact@v4
      with:
        name: mac-bin 
        path: target/debug/display

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Build
      run: |
        cargo build --verbose --bin display

    - uses: actions/upload-artifact@v4
      with:
        name: windows-bin
        path: target/debug/display.exe
