name: Rust

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install x264
      run: |
        brew install x264

    - name: Get ffmpeg libraries
      run: |
        mkdir ffmpeg && cd ffmpeg
        wget https://github.com/ColorsWind/FFmpeg-macOS/releases/download/n5.0.1-patch3/FFmpeg-shared-n5.0.1-OSX-universal.zip -O ffmpeg.zip
        unzip ffmpeg.zip

    - name: Install rust nightly
      run: |
        rustup toolchain install nightly
        rustup default nightly
      
    - name: Build display
      run: |
        export FFMPEG_DIR=$(pwd)/ffmpeg
        cargo build --verbose --bin display

    - uses: actions/upload-artifact@v4
      with:
        name: mac-bin
        path: |
          target/debug/display

  build-windows:
    runs-on: windows-latest
    env: 
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
    - uses: actions/checkout@v4
  
    - name: Install vcpkg
      run: |
        vcpkg integrate install

    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Get ffmpeg libraries
      run: |
        vcpkg install ffmpeg[core,avcodec,avformat,avfilter,avdevice,swresample,swscale,x264]:x64-windows-static-md

    - name: Install rust nightly
      run: |
        rustup toolchain install nightly
        rustup default nightly

    - name: Build display
      run: |
        cargo build --verbose --bin display

    - name: Build capture
      run: |
        cargo build --verbose --bin capture

    - uses: actions/upload-artifact@v4
      with:
        name: windows-bin
        path: |
          target/debug/display.exe
          target/debug/capture.exe
