name: Rust

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Build display
      run: |
        cargo build --verbose --bin display

    - name: Build capture
      run: |
        cargo build --verbose --bin capture

    - uses: actions/upload-artifact@v4
      with:
        name: mac-bin
        path: |
          target/debug/display
          target/debug/capture

    - name: Debug with tmate on failure
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3

  build-windows:
    runs-on: windows-latest
    env: 
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
    - uses: actions/checkout@v4
  
    - name: Install vcpkg
      run: |
        vcpkg integrate install

    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Get ffmpeg libraries
      run: |
        vcpkg install ffmpeg:x64-windows-static-md

    - name: Build display
      run: |
        cargo build --verbose --bin display

    - name: Build capture
      run: |
        cargo build --verbose --bin capture

    - uses: actions/upload-artifact@v4
      with:
        name: windows-bin
        path: |
          target/debug/display.exe
          target/debug/capture.exe

    - name: Debug with tmate on failure
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
